import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        serif: ['"Satisfy"', 'cursive'],
        sans: ['"DM Sans"', 'sans-serif'],
        heading: ['"Satisfy"', 'cursive'],
        body: ['"DM Sans"', 'sans-serif'],
        crm: ['"Inter"', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'crm-display': ['"Inter"', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'crm-body': ['"Inter"', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'crm-label': ['"Inter"', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        'crm-mono': ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        tertiary: {
          DEFAULT: "hsl(var(--tertiary))",
          foreground: "hsl(var(--tertiary-foreground))",
        },
        neutral: {
          DEFAULT: "hsl(var(--neutral))",
          foreground: "hsl(var(--neutral-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          soft: "hsl(var(--success-soft))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          soft: "hsl(var(--warning-soft))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          soft: "hsl(var(--info-soft))",
        },
        highlight: {
          DEFAULT: "hsl(var(--highlight))",
          foreground: "hsl(var(--highlight-foreground))",
        },
        "surface-warm": "hsl(var(--surface-warm))",
        "surface-0": "hsl(var(--surface-0))",
        "surface-1": "hsl(var(--surface-1))",
        "surface-2": "hsl(var(--surface-2))",
        "surface-3": "hsl(var(--surface-3))",
        "surface-4": "hsl(var(--surface-4))",
        "surface-sunken": "hsl(var(--surface-sunken))",
        hairline: "hsl(var(--hairline))",
        "hairline-strong": "hsl(var(--hairline-strong))",
        "border-strong": "hsl(var(--border-strong))",
        "accent-brand": "hsl(var(--accent-brand))",
        "accent-warm": "hsl(var(--accent-warm))",
        tag: {
          blue:   "hsl(var(--tag-blue))",
          cyan:   "hsl(var(--tag-cyan))",
          green:  "hsl(var(--tag-green))",
          yellow: "hsl(var(--tag-yellow))",
          orange: "hsl(var(--tag-orange))",
          red:    "hsl(var(--tag-red))",
          pink:   "hsl(var(--tag-pink))",
          purple: "hsl(var(--tag-purple))",
          indigo: "hsl(var(--tag-indigo))",
          teal:   "hsl(var(--tag-teal))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      boxShadow: {
        soft: "0 1px 2px 0 hsl(220 25% 14% / 0.04), 0 1px 3px 0 hsl(220 25% 14% / 0.04)",
        card: "0 4px 12px -2px hsl(220 25% 14% / 0.06), 0 2px 6px -2px hsl(220 25% 14% / 0.04)",
        pop: "0 24px 48px -12px hsl(220 25% 14% / 0.18), 0 8px 16px -8px hsl(220 25% 14% / 0.12)",
        ringed: "0 0 0 4px hsl(var(--ring) / 0.12)",
        floating: "0 12px 32px -8px hsl(220 25% 14% / 0.18), 0 4px 8px -4px hsl(220 25% 14% / 0.10), 0 0 0 1px hsl(220 14% 14% / 0.04)",
        "inset-hairline": "inset 0 0 0 1px hsl(var(--hairline))",
        "crm-xs": "var(--shadow-xs)",
        "crm-sm": "var(--shadow-sm)",
        "crm-md": "var(--shadow-md)",
        "crm-pop": "var(--shadow-pop)",
      },
      transitionDuration: {
        "crm-fast": "120ms",
        crm: "180ms",
        "crm-slow": "240ms",
      },
      transitionTimingFunction: {
        crm: "cubic-bezier(.2,.8,.2,1)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "leaf-float": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "50%": { transform: "translateY(-8px) rotate(3deg)" },
        },
        "leaf-orbit": {
          "0%": { transform: "translate(380px, 0px) rotate(0deg)", opacity: "0.6" },
          "12.5%": { transform: "translate(268px, 55px) rotate(45deg)", opacity: "0.7" },
          "25%": { transform: "translate(0px, 75px) rotate(90deg)", opacity: "0.8" },
          "37.5%": { transform: "translate(-268px, 55px) rotate(135deg)", opacity: "0.7" },
          "50%": { transform: "translate(-380px, 0px) rotate(180deg)", opacity: "0.5" },
          "62.5%": { transform: "translate(-268px, -55px) rotate(225deg)", opacity: "0.7" },
          "75%": { transform: "translate(0px, -75px) rotate(270deg)", opacity: "0.8" },
          "87.5%": { transform: "translate(268px, -55px) rotate(315deg)", opacity: "0.7" },
          "100%": { transform: "translate(380px, 0px) rotate(360deg)", opacity: "0.6" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "leaf-float": "leaf-float 7s ease-in-out infinite",
        "leaf-orbit": "leaf-orbit 30s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
